version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  CODECOV_TOKEN:
    secure: XI0zdeETuIHv1BTal3upBacJGYw8/xRIP0seISwW7/dFJvQuzoSaVT0NegCxTI8R
nuget:
  project_feed: true
before_build:
- ps: dotnet restore C:\projects\applemusicapi-net\src\
build:
  publish_nuget: true
  verbosity: minimal
test_script:
- ps: "choco install opencover.portable --limitoutput --no-progress\nchoco install codecov --limitoutput --no-progress\n\nOpenCover.Console.exe -register:user -oldstyle -returntargetcode -target:\"C:/Program Files/dotnet/dotnet.exe\" -targetargs:\"test --no-build --logger:trx;LogFileName=AppleMusicAPI.NET_results.xml /p:DebugType=full .\\src\\AppleMusicAPI.NET.Tests\\AppleMusicAPI.NET.Tests.csproj\" -filter:\"+[AppleMusicAPI.NET*]* -[AppleMusicAPI.NET.Sample*]* -[AppleMusicAPI.NET.Tests*]*\" -output:\".\\AppleMusicAPI.NET_coverage.xml\"\n \n$testRunnerErrorCode = $LASTEXITCODE\n \n$wc = New-Object 'System.Net.WebClient'\n$wc.UploadFile(\"https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)\", \"C:/projects/applemusicapi-net/src/AppleMusicAPI.NET.Tests/TestResults/AppleMusicAPI.NET_results.xml\")\n \nif ($testRunnerErrorCode -ne 0) { throw \"xUnit failed with code $testRunnerErrorCode\"}\n\ncodecov -f \"AppleMusicAPI.NET_coverage.xml\""
deploy:
- provider: NuGet
  api_key:
    secure: OZEAAZrBRyiNBJfpcfQP3COgLI6/b4nQAaLUaPMEPSrOYRN2PP+IHTRPwgx+t0UL
  on:
    branch: master
    appveyor_repo_tag: true
- provider: NuGet
  server: https://ci.appveyor.com/nuget/mattpress-hmutpeq4dlke
  api_key:
    secure: 8rnBuQCFc1kM+JbTi6YuI/sz9vzNNlbnUQgXinSrpkc=
  on:
    branch: master
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: mcrfjmcW/R+ruStDyFDHlxkFGimhWDpmqndXsSC27ZPNtt2Mw9K3KDJUtWRIHTlV
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true