version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- ps: dotnet restore C:\projects\applemusicapi-net\src\
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: OZEAAZrBRyiNBJfpcfQP3COgLI6/b4nQAaLUaPMEPSrOYRN2PP+IHTRPwgx+t0UL
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://ci.appveyor.com/nuget/mattpress-hmutpeq4dlke
  api_key:
    secure: KU4BAXP6rBGMSzIpwvexjAQZ6Pfebd5ZZaSyOzZBLVE=
  on:
    branch: master
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: mcrfjmcW/R+ruStDyFDHlxkFGimhWDpmqndXsSC27ZPNtt2Mw9K3KDJUtWRIHTlV
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true