version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: aIt5e7UEgNTIIPJcD4nNGRu9ovTAf/lQShOYRpBqdtCfwpEwxdUqi7CZO63hxvaz
nuget:
  project_feed: true
before_build:
- ps: dotnet restore C:\projects\applemusicapi-net\src\
build:
  publish_nuget: true
  verbosity: minimal
test_script:
- ps: >-
    nuget install xunit.runner.console -OutputDirectory packages -Version 2.4.0

    nuget install OpenCover -OutputDirectory packages -Version 4.6.519

    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools


    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:dotnet.exe "-targetargs:"".\packages\xunit.runner.console.2.4.0\tools\netcoreapp2.0\xunit.console.dll"" ""src\AppleMusicAPI.NET.Tests\bin\Release\netcoreapp2.1\AppleMusicAPI.NET.Tests.dll"" -noshadow -appveyor -xml AppleMusicAPI.NET_results.xml" -filter:"+[AppleMusicAPI.NET*]* -[AppleMusicAPI.NET.Sample*]* -[AppleMusicAPI.NET.Tests*]*" -oldStyle -returntargetcode -output:AppleMusicAPI.NET_coverage.xml


    $testRunnerErrorCode = $LASTEXITCODE


    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", , (Resolve-Path .\AppleMusicAPI.NET_results.xml))


    if ($testRunnerErrorCode -ne 0) { throw "xUnit failed with code: $testRunnerErrorCode"}


    $coveralls = ".\tools\csmacnz.coveralls.exe"

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
deploy:
- provider: NuGet
  api_key:
    secure: OZEAAZrBRyiNBJfpcfQP3COgLI6/b4nQAaLUaPMEPSrOYRN2PP+IHTRPwgx+t0UL
  on:
    branch: master
    appveyor_repo_tag: true
- provider: NuGet
  server: https://ci.appveyor.com/nuget/mattpress-hmutpeq4dlke
  api_key:
    secure: KU4BAXP6rBGMSzIpwvexjAQZ6Pfebd5ZZaSyOzZBLVE=
  on:
    branch: master
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: mcrfjmcW/R+ruStDyFDHlxkFGimhWDpmqndXsSC27ZPNtt2Mw9K3KDJUtWRIHTlV
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true